[package]
name = "synapse-admin-api"
version = "0.3.0"
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the synapse admin API."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
repository = "https://github.com/ruma/synapse-admin-api"
edition = "2018"

[features]
client = []
server = []
unstable-exhaustive-types = []

[dependencies]
ruma = { version = "0.6.4", features = ["api", "events"] }
serde = { version = "1.0.118", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.61"
