[package]
name = "synapse-admin-api"
version = "0.0.0"
#authors = []
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the synapse admin API."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
repository = "https://github.com/ruma/synapse-admin-api"
edition = "2018"

[dependencies]
#assign = "1.1.1"
#js_int = { version = "0.2.0", features = ["serde"] }
#ruma-api = { version = "=0.17.0-alpha.2" }
#ruma-common = { version = "=0.3.0-alpha.1" }
#ruma-events = { version = "=0.22.0-alpha.2" }
#ruma-identifiers = { version = "=0.18.0-alpha.1" }
#ruma-serde = { version = "0.3.0" }
#serde = { version = "1.0.118", features = ["derive"] }
#serde_json = "1.0.61"

[features]
#unstable-exhaustive-types = []
